spring:
  datasource:
    url: jdbc:mysql://localhost:3306/new_saveotron
    username: saveotron_admin
    password: saveotron_admin
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
# Uncomment these to let generate the schema  
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            create-source: metadata
#            scripts:
#              action: create
#              create-target: database_create.sql